shader_type spatial;
uniform sampler2D text;
uniform vec4 base_color;
uniform float speed;

void vertex() {
	vec2 base_uv = UV
	
	// Called for every vertex the material is visible on.
}

void fragment() {
	// Called for every pixel the material is visible on.
}

//void light() {
//	// Called for every pixel for every light affecting the material.
//	// Uncomment to replace the default light processing function with this one.
//}
